# ~/.config/starship.toml

[cmd_duration]
min_time = 500
prefix = "â± "


[git_status]
ahead="ğŸ”º "
behind="ğŸ”» "
untracked = "ğŸ‘»"
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"

modified_count.enabled = true

renamed_count.enabled = true

deleted = "ğŸ—‘ "
deleted_count.enabled = true
modified = "âœï¸ "
show_sync_count=true

[time]
disabled=false

[nodejs]